name: htop
version: beta
summary: htop download
description: htop is an interactive text-mode process viewer for Unix Systems. It aims to be a better top

apps:
  htop:
    command: bin/htop
parts:
  htop:
    plugin: autotools
    source: https://github.com/hishamhm/htop.git
    source-type: git
    configflags:
      - --disable-unicode
    build-packages:
      - libncurses5-dev
