name: afni
version: beta
summary: THIS IS A TEST
description: THIS IS ALSO A TEST

apps:
  afni:
    command: afni
parts:
  afni:
    source: https://afni.nimh.nih.gov/pub/dist/tgz/linux_openmp_64.tgz
    plugin: dump
