name: dax 
version: beta
summary: THIS IS A TEST
description: THIS IS ALSO A TEST
confinement: devmode

apps:
  dax-build:
    command: bin/dax_build
  run-spider:
    command: bin/run_spider
  Xnatinfo:
    command: bin/Xnatinfo
parts:
  dax:
    plugin: python2
    source: https://github.com/VUIIS/dax
    source-type: git
    stage-packages:
      - python-tk
    python-packages:
      - requests
      - lxml
      - pyxnat
      - pycap
      - httplib2
      - matplotlib
      - numpy
      - nibabel
      - pydicom
      - xlrd
