name: fail2ban
version: beta
summary: THIS IS A TEST
description: THIS IS ALSO A TEST

apps:
  fail2ban:
    command: bin/fail2ban-client
  fail2ban:
    command: bin/fail2ban-python
  fail2ban:
    command: bin/fail2ban-regex
  fail2ban:
    command: bin/fail2ban-server
  fail2ban:
    commandL bin/fail2ban-testcases


parts:
  fail2ban:
    plugin: python2
    source: https://github.com/fail2ban/fail2ban
    source-type: git 
