name: slicer
version: beta
summary: THIS IS A TEST
description: THIS IS ALSO A TEST

apps:
  slicer:
    command: usr/bin/mcverter
parts:
  slicer:
    plugin: dump
    source: http://slicer.kitware.com/midas3/download/item/258803/Slicer-4.6.0-linux-amd64.tar.gz
