name: mriconvert
version: beta
summary: THIS IS A TEST
description: THIS IS ALSO A TEST

apps:
  mriconvert:
    command: usr/bin/mcverter
  mriconvert:
    command: usr/bin/MRIConvert
parts:
  mriconvert:
    plugin: dump
    source: https://lcni.uoregon.edu/downloads/mriconvert/MRIConvert-2.1.0-amd64.tar.gz
