name: singularity
version: beta
summary: THIS IS A TEST
description: THIS IS ALSO A TEST

apps:
  singularity:
    command: bin/singularity
parts:
  singularity:
    plugin: dump
    source: https://github.com/singularityware/singularity/releases/download/2.2/singularity-2.2.tar.gz 

