name: mricron
version: beta
summary: THIS IS A TEST
description: THIS IS ALSO A TEST

apps:
  mricron:
    command: bin/mricron
parts:
  mricron:
      plugin: dump
      source: http://www.nitrc.org/frs/download.php/9322/lx.zip/?i_agree=1
