name: bmon
version: beta
summary: bmon 3.9 
description: same as above

apps:
  bmon:
    command: bin/bmon
parts:
  bmon:
    plugin: autotools
    source: https://github.com/tgraf/bmon/releases/download/v3.9/bmon-3.9.tar.gz
    build-packages:
      - libncurses5-dev
      - libconfuse-dev
      - libnl-genl-3-dev
      - libnl-route-3-dev
