name: emacs
version: beta
summary: emacs
description: same as above

apps:
  emacs:
    command: emacs
parts:
  emacs:
    plugin: autotools
    source: https://ftp.gnu.org/gnu/emacs/emacs-25.1.tar.xz 
    configflags:
      - --with-tiff=no
    build-packages:
      - libxpm-dev 
      - libjpeg-dev
      - libgif-dev 











