name: virtualbox
version: beta
summary: virtualbox
description: same as above

apps:
  virtualbox:
    command: Makefile.kmk
parts:
   virtualbox:
      plugin: dump
      source: http://download.virtualbox.org/virtualbox/5.1.10/VirtualBox-5.1.10.tar.bz2
